// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package com.starrocks.connector.thive;

import com.tencent.tdw_udf_cloud.hive.udf.AesDecryption;
import com.tencent.tdw_udf_cloud.hive.udf.AesDecryptionWithKey;
import com.tencent.tdw_udf_cloud.hive.udf.AesEncryption;
import com.tencent.tdw_udf_cloud.hive.udf.AesEncryptionWithKey;
import com.tencent.tdw_udf_cloud.hive.udf.DatahubStringToMap;
import com.tencent.tdw_udf_cloud.hive.udf.DesDecryptionWithKey;
import com.tencent.tdw_udf_cloud.hive.udf.DesEncryptionWithKey;
import com.tencent.tdw_udf_cloud.hive.udf.LogicGradeToUpperGrade;
import com.tencent.tdw_udf_cloud.hive.udf.PIIHash;
import com.tencent.tdw_udf_cloud.hive.udf.RcmdidDecoder;
import com.tencent.tdw_udf_cloud.hive.udf.SCCDateAdd;
import com.tencent.tdw_udf_cloud.hive.udf.SgameEmbededArrayDecode;
import com.tencent.tdw_udf_cloud.hive.udf.SgameEmbededArrayGetField;
import com.tencent.tdw_udf_cloud.hive.udf.SgameEmbendedArray;
import com.tencent.tdw_udf_cloud.hive.udf.SgameEmbendedArray30s;
import com.tencent.tdw_udf_cloud.hive.udf.SgameStat30s2;
import com.tencent.tdw_udf_cloud.hive.udf.ShowGradeToLogicGrade;
import com.tencent.tdw_udf_cloud.hive.udf.UDFADD_MONTHS;
import com.tencent.tdw_udf_cloud.hive.udf.UDFAbs;
import com.tencent.tdw_udf_cloud.hive.udf.UDFAcos;
import com.tencent.tdw_udf_cloud.hive.udf.UDFAscii;
import com.tencent.tdw_udf_cloud.hive.udf.UDFAsin;
import com.tencent.tdw_udf_cloud.hive.udf.UDFBKDRHash2Long;
import com.tencent.tdw_udf_cloud.hive.udf.UDFBase64;
import com.tencent.tdw_udf_cloud.hive.udf.UDFBetween;
import com.tencent.tdw_udf_cloud.hive.udf.UDFBin;
import com.tencent.tdw_udf_cloud.hive.udf.UDFBitand;
import com.tencent.tdw_udf_cloud.hive.udf.UDFCHR;
import com.tencent.tdw_udf_cloud.hive.udf.UDFCeil;
import com.tencent.tdw_udf_cloud.hive.udf.UDFCollectDbTableInfo;
import com.tencent.tdw_udf_cloud.hive.udf.UDFCommonStr;
import com.tencent.tdw_udf_cloud.hive.udf.UDFComparison;
import com.tencent.tdw_udf_cloud.hive.udf.UDFConv;
import com.tencent.tdw_udf_cloud.hive.udf.UDFConvert;
import com.tencent.tdw_udf_cloud.hive.udf.UDFCos;
import com.tencent.tdw_udf_cloud.hive.udf.UDFDateAdd;
import com.tencent.tdw_udf_cloud.hive.udf.UDFDateDiff;
import com.tencent.tdw_udf_cloud.hive.udf.UDFDateSub;
import com.tencent.tdw_udf_cloud.hive.udf.UDFDayOfMonth;
import com.tencent.tdw_udf_cloud.hive.udf.UDFExp;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFit3desDecrypt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFit3desEncrypt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitCbcDecrypt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitCbcDecrypt2;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitCbcEncrypt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitDecrypt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitDecrypt1;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitDecrypt2;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitDecrypt_1;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitEncrypt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitEncrypt1;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitEncrypt2;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitEncrypt_1;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitGetNewestKey;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitGetSalt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitGetSalt2;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitSM3Encrypt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFitSM4Decrypt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFloor;
import com.tencent.tdw_udf_cloud.hive.udf.UDFFromUnixTime;
import com.tencent.tdw_udf_cloud.hive.udf.UDFGeohashEncode;
import com.tencent.tdw_udf_cloud.hive.udf.UDFHex;
import com.tencent.tdw_udf_cloud.hive.udf.UDFHour;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIPChange;
import com.tencent.tdw_udf_cloud.hive.udf.UDFInet_aton;
import com.tencent.tdw_udf_cloud.hive.udf.UDFInet_ntoa;
import com.tencent.tdw_udf_cloud.hive.udf.UDFInstr;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIntersect;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpInfo;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpInfo2;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6AddressExtract;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6CheckInRange;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6CheckType;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6CheckVersion;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6Compare;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6FormatConvert;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6Ntop;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6Pton;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6Residual;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6SegmentExtract;
import com.tencent.tdw_udf_cloud.hive.udf.UDFIpv6SegmentFormatConvert;
import com.tencent.tdw_udf_cloud.hive.udf.UDFJson;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLAST_DAY;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLTrim;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLength;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLike;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLn;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLog;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLog10;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLog2;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLostTimeExtract;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLower;
import com.tencent.tdw_udf_cloud.hive.udf.UDFLpad;
import com.tencent.tdw_udf_cloud.hive.udf.UDFMONTHS_BETWEEN;
import com.tencent.tdw_udf_cloud.hive.udf.UDFMainDomain;
import com.tencent.tdw_udf_cloud.hive.udf.UDFMd5Hash;
import com.tencent.tdw_udf_cloud.hive.udf.UDFMd5WithHex;
import com.tencent.tdw_udf_cloud.hive.udf.UDFMinute;
import com.tencent.tdw_udf_cloud.hive.udf.UDFMod;
import com.tencent.tdw_udf_cloud.hive.udf.UDFMonth;
import com.tencent.tdw_udf_cloud.hive.udf.UDFMurmurHash;
import com.tencent.tdw_udf_cloud.hive.udf.UDFNVL;
import com.tencent.tdw_udf_cloud.hive.udf.UDFNVL2;
import com.tencent.tdw_udf_cloud.hive.udf.UDFNextDay;
import com.tencent.tdw_udf_cloud.hive.udf.UDFNumberFormat;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPBitAnd;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPBitNot;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPBitOr;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPBitShiftLeft;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPBitShiftRight;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPBitXor;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPDivide;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPDivideZeroReturnNull;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPLongDivide;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPMinus;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPMod;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPMultiply;
import com.tencent.tdw_udf_cloud.hive.udf.UDFOPPlus;
import com.tencent.tdw_udf_cloud.hive.udf.UDFParseUrl;
import com.tencent.tdw_udf_cloud.hive.udf.UDFPosMod;
import com.tencent.tdw_udf_cloud.hive.udf.UDFPower;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRTrim;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRand;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRcmdidDecoder;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRegExp;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRegExpExtract;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRegExpReplace;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRemoveDupInString;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRepeat;
import com.tencent.tdw_udf_cloud.hive.udf.UDFReverse;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRound;
import com.tencent.tdw_udf_cloud.hive.udf.UDFRpad;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSIGN;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSecond;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSessionTimeZone;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSha256;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSin;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSpace;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSqrt;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSubstr;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSurvivalTimeExtract;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSysTimestamp;
import com.tencent.tdw_udf_cloud.hive.udf.UDFSysdate;
import com.tencent.tdw_udf_cloud.hive.udf.UDFTRUNC;
import com.tencent.tdw_udf_cloud.hive.udf.UDFThiveJson;
import com.tencent.tdw_udf_cloud.hive.udf.UDFToChar;
import com.tencent.tdw_udf_cloud.hive.udf.UDFToDate2;
import com.tencent.tdw_udf_cloud.hive.udf.UDFToNumber;
import com.tencent.tdw_udf_cloud.hive.udf.UDFTrim;
import com.tencent.tdw_udf_cloud.hive.udf.UDFTz_Offset;
import com.tencent.tdw_udf_cloud.hive.udf.UDFUinChange;
import com.tencent.tdw_udf_cloud.hive.udf.UDFUnbase64;
import com.tencent.tdw_udf_cloud.hive.udf.UDFUnhex;
import com.tencent.tdw_udf_cloud.hive.udf.UDFUnicodeToUTF8String;
import com.tencent.tdw_udf_cloud.hive.udf.UDFUnixTimeStamp;
import com.tencent.tdw_udf_cloud.hive.udf.UDFUpper;
import com.tencent.tdw_udf_cloud.hive.udf.UDFWeek;
import com.tencent.tdw_udf_cloud.hive.udf.UDFWeekOfYear;
import com.tencent.tdw_udf_cloud.hive.udf.UDFYear;
import com.tencent.tdw_udf_cloud.hive.udf.UDFYearAndMonth;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFAesCbc256DecryptionWithToken;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFAesCbc256EncryptionWithToken;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFArray;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFArrayContains;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFBase64;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFCalCharNum;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFCase;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFCoalesce;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFConcatWS;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFDECODE201612;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFDecode;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFElt;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFFromUtcTimestamp;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFGeohashDecode;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFGreatest;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFHiveStringToMap;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFIf;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFIndex;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFJettyUrlDecode;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFLeast;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFLocate;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFMap;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFMapKeys;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFMapValues;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFOneBetween;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFParseQQFriendFlag;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFParseSimpleJson;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFParseUrlParams;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFParseXmlContent;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFParseXmlCount;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFRc4;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFRegExpInstr;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFSentences;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFSha2;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFSize;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFSortArray;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFSplit;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFStringToMap;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFStruct;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFSubstringIndex;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFTestGBK;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFToUtcTimestamp;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFUnBase64;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFUnicode;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFUnion;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFUrlDecode;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFUrlEncode;
import com.tencent.tdw_udf_cloud.hive.udf.generic.GenericUDFWhen;
import com.tencent.tdw_udf_cloud.hive.udf.generic.SM4GCMDecryptNoPadding;
import com.tencent.tdw_udf_cloud.hive.udf.generic.SM4GCMEncryptNoPadding;
import com.tencent.tdw_udf_cloud.hive.udf.generic.UDFBkdr;
import org.apache.hadoop.hive.ql.exec.FunctionInfo;
import org.apache.hadoop.hive.ql.exec.Registry;
import org.apache.hadoop.hive.ql.udf.generic.GenericUDFCharacterLength;
import org.apache.hadoop.hive.ql.udf.generic.GenericUDFHash;

import java.util.Set;

public class ThiveFunctionRegistry {
    private ThiveFunctionRegistry() {
    }

    // registry for hive functions
    private static final Registry SYSTEM = new Registry(false);

    static {
        // register TDW hive UDF
        SYSTEM.registerGenericUDF("struct", GenericUDFStruct.class);
        SYSTEM.registerGenericUDF("case", GenericUDFCase.class);
        SYSTEM.registerGenericUDF("when", GenericUDFWhen.class);
        SYSTEM.registerGenericUDF("coalesce", GenericUDFCoalesce.class);
        SYSTEM.registerGenericUDF("index", GenericUDFIndex.class);
        SYSTEM.registerGenericUDF("locate", GenericUDFLocate.class);
        SYSTEM.registerGenericUDF("elt", GenericUDFElt.class);
        SYSTEM.registerGenericUDF("greatest", GenericUDFGreatest.class);
        SYSTEM.registerGenericUDF("least", GenericUDFLeast.class);
        SYSTEM.registerGenericUDF("regexp_instr", GenericUDFRegExpInstr.class);
        SYSTEM.registerGenericUDF("url_encode", GenericUDFUrlEncode.class);
        SYSTEM.registerGenericUDF("url_decode", GenericUDFUrlDecode.class);
        SYSTEM.registerGenericUDF("datahub_url_decode", GenericUDFJettyUrlDecode.class);
        SYSTEM.registerGenericUDF("unicode", GenericUDFUnicode.class);
        SYSTEM.registerGenericUDF("parse_qqfriend_flag", GenericUDFParseQQFriendFlag.class);
        SYSTEM.registerGenericUDF("rc4", GenericUDFRc4.class);
        SYSTEM.registerGenericUDF("gbk2utf8", GenericUDFTestGBK.class);
        SYSTEM.registerUDF("uniq_str", UDFRemoveDupInString.class, false);
        SYSTEM.registerUDF("md5_hex", UDFMd5WithHex.class, false);
        SYSTEM.registerGenericUDF("get_char_num", GenericUDFCalCharNum.class);

        SYSTEM.registerGenericUDF("map_keys", GenericUDFMapKeys.class);
        SYSTEM.registerGenericUDF("map_values", GenericUDFMapValues.class);
        SYSTEM.registerGenericUDF("concat_ws", GenericUDFConcatWS.class);
        SYSTEM.registerGenericUDF("sort_array", GenericUDFSortArray.class);
        SYSTEM.registerGenericUDF("substring_index", GenericUDFSubstringIndex.class);

        SYSTEM.registerUDF("ipv6_pton", UDFIpv6Pton.class, true, "ipv6_pton");
        SYSTEM.registerUDF("ipv6_ntop", UDFIpv6Ntop.class, true, "ipv6_ntop");
        SYSTEM.registerUDF("ipv6_extract", UDFIpv6AddressExtract.class, true, "ipv6_extract");
        SYSTEM.registerUDF("ipv6_in_range", UDFIpv6CheckInRange.class, true, "ipv6_in_range");
        SYSTEM.registerUDF("ipv6_type", UDFIpv6CheckType.class, true, "ipv6_type");
        SYSTEM.registerUDF("ip_version", UDFIpv6CheckVersion.class, true, "ip_version");
        SYSTEM.registerUDF("ipv6_compare", UDFIpv6Compare.class, true, "ipv6_compare");
        SYSTEM.registerUDF("ipv6_convert", UDFIpv6FormatConvert.class, true, "ipv6_convert");
        SYSTEM.registerUDF("ipv6_residual", UDFIpv6Residual.class, true, "ipv6_residual");
        SYSTEM.registerUDF("ipv6_seg_ext", UDFIpv6SegmentExtract.class, true, "ipv6_seg_ext");
        SYSTEM.registerUDF("ipv6_seg_cvt", UDFIpv6SegmentFormatConvert.class, true, "ipv6_seg_cvt");
        SYSTEM.registerUDF("unicode_utf8", UDFUnicodeToUTF8String.class, true, "unicode_utf8");
        SYSTEM.registerUDF("ipinfo2", UDFIpInfo2.class, false);

        SYSTEM.registerGenericUDF("da5223ca0d", GenericUDFDECODE201612.class);

        SYSTEM.registerUDF("collect_sql_db_table_list", UDFCollectDbTableInfo.class, false);
        SYSTEM.registerUDF("LogicGradeToUpperGrade", LogicGradeToUpperGrade.class, false);
        SYSTEM.registerUDF("SgameEmbendedArray", SgameEmbendedArray.class, false);
        SYSTEM.registerUDF("SgameEmbendedArray30s", SgameEmbendedArray30s.class, false);
        SYSTEM.registerUDF("SgameStat30s2", SgameStat30s2.class, false);
        SYSTEM.registerUDF("SCCDateAdd", SCCDateAdd.class, false);
        SYSTEM.registerUDF("SgameEmbededArrayDecode", SgameEmbededArrayDecode.class, false);
        SYSTEM.registerUDF("SgameEmbededArrayGetField", SgameEmbededArrayGetField.class, false);
        SYSTEM.registerUDF("ShowGradeToLogicGrade", ShowGradeToLogicGrade.class, false);

        SYSTEM.registerUDF("decode_rcmdid", RcmdidDecoder.class, false);
        SYSTEM.registerUDF("rand", UDFRand.class, false);
        SYSTEM.registerUDF("systimestamp", UDFSysTimestamp.class, true, "systimestamp");
        SYSTEM.registerGenericUDF("hash", GenericUDFHash.class);
        SYSTEM.registerGenericUDF("oneBetween", GenericUDFOneBetween.class);
        SYSTEM.registerUDF("uinchange", UDFUinChange.class, false);
        SYSTEM.registerUDF("ipchange", UDFIPChange.class, false);
        SYSTEM.registerUDF("md5", UDFMd5Hash.class, false);
        SYSTEM.registerUDF("murmurHash", UDFMurmurHash.class, false);
        SYSTEM.registerUDF("str_hash_bigint", UDFBKDRHash2Long.class, false);
        SYSTEM.registerUDF("AesEncryption", AesEncryption.class, false);
        SYSTEM.registerUDF("AesDecryption", AesDecryption.class, false);
        SYSTEM.registerUDF("AesEncryptionWithKey", AesEncryptionWithKey.class, false);
        SYSTEM.registerUDF("AesDecryptionWithKey", AesDecryptionWithKey.class, false);
        SYSTEM.registerUDF("DesEncryptionWithKey", DesEncryptionWithKey.class, false);
        SYSTEM.registerUDF("DesDecryptionWithKey", DesDecryptionWithKey.class, false);
        SYSTEM.registerGenericUDF("AesEncryptionWithToken", GenericUDFAesCbc256EncryptionWithToken.class);
        SYSTEM.registerGenericUDF("AesDecryptionWithToken", GenericUDFAesCbc256DecryptionWithToken.class);
        SYSTEM.registerUDF("fit_encrypt", UDFFitEncrypt.class, false);
        SYSTEM.registerUDF("fit_decrypt", UDFFitDecrypt.class, false);
        SYSTEM.registerUDF("fit_encrypt_1", UDFFitEncrypt_1.class, false);
        SYSTEM.registerUDF("fit_decrypt_1", UDFFitDecrypt_1.class, false);
        SYSTEM.registerUDF("fit_encrypt1", UDFFitEncrypt1.class, false);
        SYSTEM.registerUDF("fit_decrypt1", UDFFitDecrypt1.class, false);
        SYSTEM.registerUDF("fit_encrypt2", UDFFitEncrypt2.class, false);
        SYSTEM.registerUDF("fit_decrypt2", UDFFitDecrypt2.class, false);
        SYSTEM.registerUDF("fit_cbc_decrypt", UDFFitCbcDecrypt.class, false);
        SYSTEM.registerUDF("fit_cbc_decrypt2", UDFFitCbcDecrypt2.class, false);
        SYSTEM.registerUDF("fit_cbc_encrypt", UDFFitCbcEncrypt.class, false);
        SYSTEM.registerUDF("fit_3des_decrypt", UDFFit3desDecrypt.class, false);
        SYSTEM.registerUDF("fit_3des_encrypt", UDFFit3desEncrypt.class, false);
        SYSTEM.registerUDF("fit_get_salt", UDFFitGetSalt.class, false);
        SYSTEM.registerUDF("fit_get_salt2", UDFFitGetSalt2.class, false);
        SYSTEM.registerUDF("fit_get_newest_key", UDFFitGetNewestKey.class, false);
        SYSTEM.registerUDF("fit_sm3_encrypt", UDFFitSM3Encrypt.class, false);
        SYSTEM.registerUDF("fit_sm4_decrypt", UDFFitSM4Decrypt.class, false);
        SYSTEM.registerUDF("LostTimeExtract", UDFLostTimeExtract.class, false);
        SYSTEM.registerUDF("SurvivalTimeExtract", UDFSurvivalTimeExtract.class, false);
        SYSTEM.registerGenericUDF("sm4_GCMDecryptNoPadding", SM4GCMDecryptNoPadding.class);
        SYSTEM.registerGenericUDF("sm4_GCMEncryptNoPadding", SM4GCMEncryptNoPadding.class);
        SYSTEM.registerGenericUDF("sentences", GenericUDFSentences.class);
        SYSTEM.registerGenericUDF("create_union", GenericUDFUnion.class);
        SYSTEM.registerUDF("substr", UDFSubstr.class, false);
        SYSTEM.registerUDF("substring", UDFSubstr.class, false);
        SYSTEM.registerUDF("space", UDFSpace.class, false);
        SYSTEM.registerUDF("repeat", UDFRepeat.class, false);
        SYSTEM.registerUDF("ascii", UDFAscii.class, false);
        SYSTEM.registerUDF("lpad", UDFLpad.class, false);
        SYSTEM.registerUDF("rpad", UDFRpad.class, false);
        SYSTEM.registerUDF("ipinfo", UDFIpInfo.class, false);
        SYSTEM.registerGenericUDF("size", GenericUDFSize.class);
        SYSTEM.registerGenericUDF("from_utc_timestamp", GenericUDFFromUtcTimestamp.class);
        SYSTEM.registerGenericUDF("to_utc_timestamp", GenericUDFToUtcTimestamp.class);
        SYSTEM.registerUDF("sign", UDFSIGN.class, false);
        SYSTEM.registerUDF("add_months", UDFADD_MONTHS.class, false);
        SYSTEM.registerUDF("trunc", UDFTRUNC.class, false);
        SYSTEM.registerUDF("numformat", UDFNumberFormat.class, false);
        SYSTEM.registerUDF("convert", UDFConvert.class, false);
        SYSTEM.registerUDF("months_between", UDFMONTHS_BETWEEN.class, false);
        SYSTEM.registerUDF("last_day", UDFLAST_DAY.class, false);
        SYSTEM.registerUDF("sessiontimezone", UDFSessionTimeZone.class, false);
        SYSTEM.registerUDF("tz_offset", UDFTz_Offset.class, false);
        SYSTEM.registerUDF("chr", UDFCHR.class, false);
        SYSTEM.registerUDF("between", UDFBetween.class, true);

        SYSTEM.registerGenericUDF("decode", GenericUDFDecode.class);
        SYSTEM.registerUDF("round", UDFRound.class, false);
        SYSTEM.registerUDF("floor", UDFFloor.class, false);
        SYSTEM.registerUDF("sqrt", UDFSqrt.class, false);
        SYSTEM.registerUDF("ceil", UDFCeil.class, false);
        SYSTEM.registerUDF("ceiling", UDFCeil.class, false);
        SYSTEM.registerUDF("abs", UDFAbs.class, false);
        SYSTEM.registerUDF("pmod", UDFPosMod.class, false);
        SYSTEM.registerUDF("ln", UDFLn.class, false);
        SYSTEM.registerUDF("log2", UDFLog2.class, false);
        SYSTEM.registerUDF("sin", UDFSin.class, false);
        SYSTEM.registerUDF("asin", UDFAsin.class, false);
        SYSTEM.registerUDF("cos", UDFCos.class, false);
        SYSTEM.registerUDF("acos", UDFAcos.class, false);
        SYSTEM.registerUDF("log10", UDFLog10.class, false);
        SYSTEM.registerUDF("log", UDFLog.class, false);
        SYSTEM.registerUDF("exp", UDFExp.class, false);
        SYSTEM.registerUDF("power", UDFPower.class, false);
        SYSTEM.registerUDF("pow", UDFPower.class, false);
        SYSTEM.registerUDF("conv", UDFConv.class, false);
        SYSTEM.registerUDF("bin", UDFBin.class, false);
        SYSTEM.registerUDF("hex", UDFHex.class, false);
        SYSTEM.registerUDF("hive_hex", org.apache.hadoop.hive.ql.udf.UDFHex.class, false);
        SYSTEM.registerUDF("unhex", UDFUnhex.class, false);
        SYSTEM.registerUDF("upper", UDFUpper.class, false);
        SYSTEM.registerUDF("lower", UDFLower.class, false);
        SYSTEM.registerUDF("ucase", UDFUpper.class, false);
        SYSTEM.registerUDF("lcase", UDFLower.class, false);
        SYSTEM.registerUDF("trim", UDFTrim.class, false);
        SYSTEM.registerUDF("ltrim", UDFLTrim.class, false);
        SYSTEM.registerUDF("rtrim", UDFRTrim.class, false);
        SYSTEM.registerUDF("length", UDFLength.class, false);
        SYSTEM.registerUDF("reverse", UDFReverse.class, false);
        SYSTEM.registerUDF("like", UDFLike.class, true);
        SYSTEM.registerUDF("rlike", UDFRegExp.class, true);
        SYSTEM.registerUDF("regexp", UDFRegExp.class, true);
        SYSTEM.registerUDF("regexp_replace", UDFRegExpReplace.class, false);
        SYSTEM.registerUDF("regexp_extract", UDFRegExpExtract.class, false);
        SYSTEM.registerUDF("pii_hash", PIIHash.class, false);
        SYSTEM.registerUDF("parse_url", UDFParseUrl.class, false);
        SYSTEM.registerGenericUDF("char_length", GenericUDFCharacterLength.class);
        SYSTEM.registerGenericUDF("split", GenericUDFSplit.class);
        SYSTEM.registerGenericUDF("string_to_map", GenericUDFStringToMap.class);
        SYSTEM.registerGenericUDF("str_to_map", GenericUDFHiveStringToMap.class);
        SYSTEM.registerGenericUDF("parse_xml_count", GenericUDFParseXmlCount.class);
        SYSTEM.registerGenericUDF("parse_xml_content", GenericUDFParseXmlContent.class);
        SYSTEM.registerGenericUDF("parse_simple_json", GenericUDFParseSimpleJson.class);
        SYSTEM.registerGenericUDF("parse_url_params", GenericUDFParseUrlParams.class);
        SYSTEM.registerGenericUDF("array_contains", GenericUDFArrayContains.class);
        SYSTEM.registerGenericUDF("array", GenericUDFArray.class);
        SYSTEM.registerGenericUDF("tdw_map", GenericUDFMap.class);
        SYSTEM.registerUDF("datahub_string_to_map", DatahubStringToMap.class, false);
        SYSTEM.registerUDF("day", UDFDayOfMonth.class, false);
        SYSTEM.registerUDF("dayofmonth", UDFDayOfMonth.class, false);
        SYSTEM.registerUDF("month", UDFMonth.class, false);
        SYSTEM.registerUDF("year", UDFYear.class, false);
        SYSTEM.registerUDF("from_unixtime", UDFFromUnixTime.class, false);
        SYSTEM.registerUDF("unix_timestamp", UDFUnixTimeStamp.class, false);
        SYSTEM.registerUDF("hour", UDFHour.class, false);
        SYSTEM.registerUDF("minute", UDFMinute.class, false);
        SYSTEM.registerUDF("second", UDFSecond.class, false);
        SYSTEM.registerUDF("weekofyear", UDFWeekOfYear.class, false);
        SYSTEM.registerUDF("year_and_month", UDFYearAndMonth.class, false);
        SYSTEM.registerUDF("commonStr", UDFCommonStr.class, false);
        SYSTEM.registerUDF("base64", UDFBase64.class, false);
        SYSTEM.registerUDF("unbase64", UDFUnbase64.class, false);
        SYSTEM.registerGenericUDF("sha2", GenericUDFSha2.class);
        SYSTEM.registerGenericUDF("hive_base64", GenericUDFBase64.class);
        SYSTEM.registerGenericUDF("hive_unbase64", GenericUDFUnBase64.class);
        SYSTEM.registerUDF("Sha256Encryption", UDFSha256.class, false);
        SYSTEM.registerUDF("week", UDFWeek.class, false);
        SYSTEM.registerUDF("date_add", UDFDateAdd.class, false);
        SYSTEM.registerUDF("date_sub", UDFDateSub.class, false);
        SYSTEM.registerUDF("datediff", UDFDateDiff.class, false);
        SYSTEM.registerUDF("get_json_object", UDFThiveJson.class, false);
        SYSTEM.registerUDF("hive_get_json_object", UDFJson.class, false);
        SYSTEM.registerUDF("get_main_domain", UDFMainDomain.class, false);
        SYSTEM.registerUDF("geohash_encode", UDFGeohashEncode.class, false);
        SYSTEM.registerUDF("bkdr", UDFBkdr.class, false);
        SYSTEM.registerGenericUDF("geohash_decode", GenericUDFGeohashDecode.class);
        SYSTEM.registerUDF("+", UDFOPPlus.class, true);
        SYSTEM.registerUDF("-", UDFOPMinus.class, true);
        SYSTEM.registerUDF("*", UDFOPMultiply.class, true);
        SYSTEM.registerUDF("/", UDFOPDivide.class, true);
        SYSTEM.registerUDF("//", UDFOPDivideZeroReturnNull.class, true);
        SYSTEM.registerUDF("%", UDFOPMod.class, true);
        SYSTEM.registerUDF("div", UDFOPLongDivide.class, true);
        SYSTEM.registerUDF("&", UDFOPBitAnd.class, true);
        SYSTEM.registerUDF("|", UDFOPBitOr.class, true);
        SYSTEM.registerUDF("^", UDFOPBitXor.class, true);
        SYSTEM.registerUDF("~", UDFOPBitNot.class, true);
        SYSTEM.registerUDF("<<", UDFOPBitShiftLeft.class, true);
        SYSTEM.registerUDF(">>", UDFOPBitShiftRight.class, true);
        SYSTEM.registerUDF("comparison", UDFComparison.class, true);
        SYSTEM.registerUDF("nvl", UDFNVL.class, true);
        SYSTEM.registerUDF("nvl2", UDFNVL2.class, true);
        SYSTEM.registerUDF("sysdate", UDFSysdate.class, true);
        SYSTEM.registerUDF("instr", UDFInstr.class, true);
        SYSTEM.registerUDF("mod", UDFMod.class, true);
        SYSTEM.registerUDF("bitand", UDFBitand.class, true);
        SYSTEM.registerUDF("next_day", UDFNextDay.class, true);
        SYSTEM.registerUDF("to_number", UDFToNumber.class, true);
        SYSTEM.registerUDF("to_char", UDFToChar.class, true);
        SYSTEM.registerUDF("to_date", UDFToDate2.class, true);
        SYSTEM.registerUDF("inet_aton", UDFInet_aton.class, true);
        SYSTEM.registerUDF("inet_ntoa", UDFInet_ntoa.class, true);
        SYSTEM.registerUDF("intersect_count", UDFIntersect.class, true);
        SYSTEM.registerUDF("rcmdid_decoder", UDFRcmdidDecoder.class, false);
        SYSTEM.registerGenericUDF("if", GenericUDFIf.class);
    }

    public static FunctionInfo getFunctionInfo(String functionName) {
        try {
            return SYSTEM.getFunctionInfo(functionName);
        } catch (Exception e) {
            return null;
        }
    }

    public static Set<String> getCurrentFunctionNames() {
        return SYSTEM.getCurrentFunctionNames();
    }
}
