# 不同名同义，进行映射
collect_list=array_agg
collect_set=array_agg_distinct
wm_concat=group_concat
string_to_map=str_to_map
sort_array=array_sort
date_parse=str_to_date
length=char_length
nvl=ifnull
approx_percentile=percentile_approx
parse_datetime=str_to_jodatime
position=locate
percentile=percentile_cont
week=dayofweek
binary=to_binary
base64=to_base64
trunc=truncate
split=regexp_split

# spark 函数映射(不完全等价)
to_timestamp=str_to_jodatime
bit_or=bitor
date_trunc=date_trunc

# tdw 函数的 Native 实现
add_months=tdw_add_months
date_add=tdw_date_add
date_sub=tdw_date_sub
to_char=tdw_to_char
to_date=tdw_to_date
to_number=tdw_bigint
boolean=tdw_boolean
tinyint=tdw_tinyint
smallint=tdw_smallint
int=tdw_int
bigint=tdw_bigint
float=tdw_float
double=tdw_double
string=tdw_string
boolean1=tdw_boolean
tinyint1=tdw_tinyint
smallint1=tdw_smallint
int1=tdw_int
bigint1=tdw_bigint
float1=tdw_float
double1=tdw_double
string1=tdw_string
boolean2=tdw_boolean
tinyint2=tdw_tinyint
smallint2=tdw_smallint
int2=tdw_int
bigint2=tdw_bigint
float2=tdw_float
double2=tdw_double
string2=tdw_string

# 同名不同义,优先使用 thive 函数
get_json_object=__thive_udf_db_.get_json_object
regexp_replace=__thive_udf_db_.regexp_replace

# 开启后优先使用 thive udf 实现，性能会有影响
# last_day=__thive_udf_db_.last_day
# unix_timestamp=__thive_udf_db_.unix_timestamp
# hour=__thive_udf_db_.hour
# minute=__thive_udf_db_.minute
# second=__thive_udf_db_.second

# 禁用函数
# e.g.
# xxxxxx=__DISABLE__
# Spark 函数,同名不同义
# timestamp=__DISABLE__